### ISSUE TITLE
Limited information on syntax error

### ISSUE THREAD

**Issue by Amzy7** [SOF3/pharynx#9] opened 2023-07-04 17:08 UTC
Once an error occurs I only receive limited information on the syntax error. For example: "Parse error: syntax error, unexpected token "{" in on line 62". Normally, you would get the pathing, file name, line number, the error, and a stack trace. However, in my case, I would only get a Line number, an error and that's it. There's no pathing to the file which makes it extremely difficult to solve the issue as you don't even know where the issue resigns.

**Comment by SOF3** [comment] 2023-07-05 15:16
duplicate of #7, sorry forgot about it

**Closed by SOF3** 2023-07-05 15:16 UTC
Labels: bug
